[build]
  command = "react-scripts build"
  commandOrigin = "ui"
  publish = "/opt/build/repo/build"
  publishOrigin = "config"

functionsDirectory = "/opt/build/repo/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status =  200
  